"""orders and order tracking

Revision ID: 0a99c4073293
Revises: aa45bd27b7f8
Create Date: 2026-08-24 20:36:07.534479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a99c4073293'
down_revision: Union[str, Sequence[str], None] = 'aa45bd27b7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_pincode', sa.String(length=6), nullable=False),
    sa.Column('pickup_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_zone_id', sa.UUID(), nullable=False),
    sa.Column('drop_address', sa.String(length=500), nullable=False),
    sa.Column('drop_pincode', sa.String(length=6), nullable=False),
    sa.Column('drop_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('drop_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('drop_zone_id', sa.UUID(), nullable=False),
    sa.Column('length_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('breadth_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumetric_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('chargeable_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('payment_type', sa.String(length=10), nullable=False),
    sa.Column('base_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cod_surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'CANCELLED', name='ck_orders_status', native_enum=False, create_constraint=True, length=20), server_default='PENDING', nullable=False),
    sa.Column('delivery_attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scheduled_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drop_zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_assigned_agent_id'), 'orders', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('order_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'CANCELLED', name='ck_order_tracking_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_tracking_order_id'), 'order_tracking', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_tracking_order_id'), table_name='order_tracking')
    op.drop_table('order_tracking')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_assigned_agent_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
