"""agent profiles table

Revision ID: 9621a8fea164
Revises: ee4a9f5b4650
Create Date: 2026-08-24 21:34:45.499050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9621a8fea164'
down_revision: Union[str, Sequence[str], None] = 'ee4a9f5b4650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='ck_agent_profiles_availability', native_enum=False, create_constraint=True, length=10), server_default='AVAILABLE', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_zone_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_agent_profiles_availability_status'), 'agent_profiles', ['availability_status'], unique=False)
    # NOTE: the three drop_constraint lines autogenerate emits for ck_users_role /
    # ck_orders_status / ck_order_tracking_status are spurious (naming-compare false
    # positive) and have been stripped — see AGENTS.md.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_agent_profiles_availability_status'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
