"""zones areas rate cards cod rates

Revision ID: aa45bd27b7f8
Revises: a80296732d4b
Create Date: 2026-08-24 20:12:26.705317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa45bd27b7f8'
down_revision: Union[str, Sequence[str], None] = 'a80296732d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cod_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_type')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pincode', name='uq_areas_pincode')
    )
    op.create_index(op.f('ix_areas_pincode'), 'areas', ['pincode'], unique=False)
    op.create_table('rate_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('from_zone_id', sa.UUID(), nullable=False),
    sa.Column('to_zone_id', sa.UUID(), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_type', 'from_zone_id', 'to_zone_id', name='uq_rate_cards_scope')
    )
    # NOTE: autogenerate spuriously reports ck_users_role as removed; it exists and must stay.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_areas_pincode'), table_name='areas')
    op.drop_table('areas')
    op.drop_table('zones')
    op.drop_table('cod_rates')
    # ### end Alembic commands ###
